In [43]:
import pandas as pd
%load_ext autoreload
%autoreload 2
import sys
import os
sys.path.append(os.path.abspath('..'))
from src.persian_to_english import persian_to_english_digits
raw_home_data = pd.read_csv("../divar_full_data.csv")
raw_home_data.head()
raw_home_data.info()
raw_home_data.describe(include='all')
raw_home_data.head(20)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10380 entries, 0 to 10379
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Token        10380 non-null  object
 1   District     10380 non-null  object
 2   Area         9792 non-null   object
 3   Year         9792 non-null   object
 4   Rooms        9792 non-null   object
 5   Floor        9257 non-null   object
 6   Parking      9792 non-null   object
 7   Storage      9792 non-null   object
 8   Elevator     9257 non-null   object
 9   Exact_Price  10380 non-null  int64
dtypes: int64(1), object(9)
memory usage: 811.1+ KB

,Token,District,Area,Year,Rooms,Floor,Parking,Storage,Elevator,Exact_Price
0,gaA4KADO,سنگلج (شاپور),NaN,NaN,NaN,NaN,NaN,NaN,NaN,20000000000
1,Qa1DsWJ1,جوانمردان (اندیشه),۷۵,۱۴۰۰,۲,۲,True,True,True,4819999744
2,Qawrev5W,خواجه نصیر طوسی,۱۲۴,۱۴۰۳,۳,۵ از ۵,True,True,True,29699999744
3,gaDEeI84,ابوذر,۵۵,۱۳۸۲,۱,۲ از ۷,False,False,False,8999999488
4,Qa9nZ1nq,خواجه نصیر طوسی,۹۳,۱۴۰۳,۲,۳,True,True,True,22320001024
5,Qa83KNv-,دریاچه شهدای خلیج فارس,۱۰۰,۱۴۰۴,۲,۱۵,True,True,True,2500000000
6,gaD4910f,تهرانپارس شرقی,۱۲۵,۱۴۰۱,۲,۳ از ۶,True,True,True,18749999104
7,gaC8NaqF,زرگنده,۱۶۵,۱۳۸۰,۳,همکف از ۵,True,True,True,51999997952
8,gaDs9Sss,استخر,۷۵,۱۳۹۰,۲,۲ از ۴,True,True,True,14000000000
9,gaDstP3o,افسریه جنوبی,۷۳,۱۳۹۹,۲,۱ از ۵,False,False,True,7900000256
10,Qa4_UQvL,سعادت‌آباد,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210000003072
11,Qa-rdUjz,دروس,۲۱۳,۱۴۰۴,۳,۵ از ۶,True,True,True,138449993728
12,Qa-XNaIP,قلهک,۱۴۷,۱۴۰۲,۲,۹ از ۹,True,True,True,124950003712
13,gaA8lFWY,دروس,۲۴۰,۱۴۰۵,۳,۶ از ۶,True,True,True,204000002048
14,Qa_fwbHD,دروس,۲۲۳,۱۴۰۲,۳,۱۰ از ۱۰,True,True,True,167250001920
15,Qax_wUwb,تهرانسر شمالی,۸۲,۱۴۰۴,۲,۳,True,True,True,16000000000
16,gaD02JW_,دریا,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325000003584
17,Qa7XgKy4,مرزداران,۸۱,۱۴۰۴,۲,۷ از ۱۱,True,True,True,12000000000
18,Qa7PhOTg,دریاچه شهدای خلیج فارس,۱۰۹,۱۴۰۴,۲,۹ از ۱۶,True,True,True,19540000768
19,gaDAd1n_,پونک,۷۵,۱۳۸۴,۲,همکف,True,True,False,18499999744

In [44]:
cols_to_convert = ["Area", "Year", "Rooms", "Floor"]
for col in cols_to_convert:
    raw_home_data[col] = raw_home_data[col].apply(persian_to_english_digits)
    
raw_home_data["Area"] = pd.to_numeric(raw_home_data["Area"], errors="coerce")
raw_home_data["Year"] = pd.to_numeric(raw_home_data["Year"], errors="coerce")
raw_home_data["Rooms"] = pd.to_numeric(raw_home_data["Rooms"], errors="coerce")



for col in ["Parking", "Storage", "Elevator"]:
    raw_home_data[col] = raw_home_data[col].fillna(False).astype(bool)
    
raw_home_data.head()

raw_home_data.info()
raw_home_data["Floor"].value_counts(dropna=False).head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10380 entries, 0 to 10379
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Token        10380 non-null  object
 1   District     10380 non-null  object
 2   Area         9792 non-null   float64
 3   Year         9693 non-null   float64
 4   Rooms        9772 non-null   float64
 5   Floor        9257 non-null   object
 6   Parking      10380 non-null  bool
 7   Storage      10380 non-null  bool
 8   Elevator     10380 non-null  bool
 9   Exact_Price  10380 non-null  int64
dtypes: bool(3), float64(3), int64(1), object(3)
memory usage: 598.2+ KB

/var/folders/33/1_9c8vl1123ffv0k7k3c_44c0000gn/T/ipykernel_17721/1881702176.py:12: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  raw_home_data[col] = raw_home_data[col].fillna(False).astype(bool)
/var/folders/33/1_9c8vl1123ffv0k7k3c_44c0000gn/T/ipykernel_17721/1881702176.py:12: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  raw_home_data[col] = raw_home_data[col].fillna(False).astype(bool)
/var/folders/33/1_9c8vl1123ffv0k7k3c_44c0000gn/T/ipykernel_17721/1881702176.py:12: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  raw_home_data[col] = raw_home_data[col].fillna(False).astype(bool)

Floor
2         1281
NaN       1123
3         1100
1          978
4          850
5          490
3 از 5     327
1 از 5     311
2 از 5     311
1 از 4     297
5 از 5     295
4 از 5     287
2 از 4     285
3 از 4     267
4 از 4     234
6          162
همکف       109
2 از 3      97
1 از 3      85
3 از 3      72
Name: count, dtype: int64

In [45]:
raw_home_data.describe(include="all")

,Token,District,Area,Year,Rooms,Floor,Parking,Storage,Elevator,Exact_Price
count,10380,10380,9.792000e+03,9693.000000,9772.000000,9257,10380,10380,10380,1.038000e+04
unique,10380,361,NaN,NaN,NaN,301,2,2,2,NaN
top,gaA4KADO,شهر زیبا,NaN,NaN,NaN,2,True,True,True,NaN
freq,1,252,NaN,NaN,NaN,1281,8121,8983,7296,NaN
mean,NaN,NaN,2.481485e+02,1395.599195,2.076648,NaN,NaN,NaN,NaN,1.790577e+11
std,NaN,NaN,1.082066e+04,8.466778,0.780191,NaN,NaN,NaN,NaN,7.116300e+12
min,NaN,NaN,0.000000e+00,1371.000000,1.000000,NaN,NaN,NaN,NaN,1.000000e+03
25%,NaN,NaN,6.500000e+01,1389.000000,2.000000,NaN,NaN,NaN,NaN,7.300000e+09
50%,NaN,NaN,9.000000e+01,1398.000000,2.000000,NaN,NaN,NaN,NaN,1.650000e+10
75%,NaN,NaN,1.300000e+02,1404.000000,3.000000,NaN,NaN,NaN,NaN,3.500000e+10
max,NaN,NaN,1.050640e+06,1405.000000,4.000000,NaN,NaN,NaN,NaN,5.200000e+14

In [46]:
import re
import numpy as np
def extract_floor_number(text):
    if pd.isna(text):
        return np.nan
    text = str(text).strip()
    if 'همکف' in text and 'زیر' not in text:
        return 0.0
    if 'زیر' in text: 
        return -1.0
        
    match = re.search(r'\d+', text)
    if match:
        return float(match.group())
        
    return np.nan
raw_home_data['Floor'] = raw_home_data['Floor'].apply(extract_floor_number)

In [47]:
raw_home_data.head(20)

,Token,District,Area,Year,Rooms,Floor,Parking,Storage,Elevator,Exact_Price
0,gaA4KADO,سنگلج (شاپور),NaN,NaN,NaN,NaN,False,False,False,20000000000
1,Qa1DsWJ1,جوانمردان (اندیشه),75.0,1400.0,2.0,2.0,True,True,True,4819999744
2,Qawrev5W,خواجه نصیر طوسی,124.0,1403.0,3.0,5.0,True,True,True,29699999744
3,gaDEeI84,ابوذر,55.0,1382.0,1.0,2.0,False,False,False,8999999488
4,Qa9nZ1nq,خواجه نصیر طوسی,93.0,1403.0,2.0,3.0,True,True,True,22320001024
5,Qa83KNv-,دریاچه شهدای خلیج فارس,100.0,1404.0,2.0,15.0,True,True,True,2500000000
6,gaD4910f,تهرانپارس شرقی,125.0,1401.0,2.0,3.0,True,True,True,18749999104
7,gaC8NaqF,زرگنده,165.0,1380.0,3.0,0.0,True,True,True,51999997952
8,gaDs9Sss,استخر,75.0,1390.0,2.0,2.0,True,True,True,14000000000
9,gaDstP3o,افسریه جنوبی,73.0,1399.0,2.0,1.0,False,False,True,7900000256
10,Qa4_UQvL,سعادت‌آباد,NaN,NaN,NaN,NaN,False,False,False,210000003072
11,Qa-rdUjz,دروس,213.0,1404.0,3.0,5.0,True,True,True,138449993728
12,Qa-XNaIP,قلهک,147.0,1402.0,2.0,9.0,True,True,True,124950003712
13,gaA8lFWY,دروس,240.0,1405.0,3.0,6.0,True,True,True,204000002048
14,Qa_fwbHD,دروس,223.0,1402.0,3.0,10.0,True,True,True,167250001920
15,Qax_wUwb,تهرانسر شمالی,82.0,1404.0,2.0,3.0,True,True,True,16000000000
16,gaD02JW_,دریا,NaN,NaN,NaN,NaN,False,False,False,325000003584
17,Qa7XgKy4,مرزداران,81.0,1404.0,2.0,7.0,True,True,True,12000000000
18,Qa7PhOTg,دریاچه شهدای خلیج فارس,109.0,1404.0,2.0,9.0,True,True,True,19540000768
19,gaDAd1n_,پونک,75.0,1384.0,2.0,0.0,True,True,False,18499999744

In [48]:
clean_data = raw_home_data.dropna(subset=['Area', 'Year', 'Rooms', 'Floor']).copy()
clean_data.reset_index(drop=True, inplace=True)
clean_data.info()
clean_data.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9173 entries, 0 to 9172
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Token        9173 non-null   object
 1   District     9173 non-null   object
 2   Area         9173 non-null   float64
 3   Year         9173 non-null   float64
 4   Rooms        9173 non-null   float64
 5   Floor        9173 non-null   float64
 6   Parking      9173 non-null   bool
 7   Storage      9173 non-null   bool
 8   Elevator     9173 non-null   bool
 9   Exact_Price  9173 non-null   int64
dtypes: bool(3), float64(4), int64(1), object(2)
memory usage: 528.6+ KB

,Token,District,Area,Year,Rooms,Floor,Parking,Storage,Elevator,Exact_Price
0,Qa1DsWJ1,جوانمردان (اندیشه),75.0,1400.0,2.0,2.0,True,True,True,4819999744
1,Qawrev5W,خواجه نصیر طوسی,124.0,1403.0,3.0,5.0,True,True,True,29699999744
2,gaDEeI84,ابوذر,55.0,1382.0,1.0,2.0,False,False,False,8999999488
3,Qa9nZ1nq,خواجه نصیر طوسی,93.0,1403.0,2.0,3.0,True,True,True,22320001024
4,Qa83KNv-,دریاچه شهدای خلیج فارس,100.0,1404.0,2.0,15.0,True,True,True,2500000000
5,gaD4910f,تهرانپارس شرقی,125.0,1401.0,2.0,3.0,True,True,True,18749999104
6,gaC8NaqF,زرگنده,165.0,1380.0,3.0,0.0,True,True,True,51999997952
7,gaDs9Sss,استخر,75.0,1390.0,2.0,2.0,True,True,True,14000000000
8,gaDstP3o,افسریه جنوبی,73.0,1399.0,2.0,1.0,False,False,True,7900000256
9,Qa-rdUjz,دروس,213.0,1404.0,3.0,5.0,True,True,True,138449993728
10,Qa-XNaIP,قلهک,147.0,1402.0,2.0,9.0,True,True,True,124950003712
11,gaA8lFWY,دروس,240.0,1405.0,3.0,6.0,True,True,True,204000002048
12,Qa_fwbHD,دروس,223.0,1402.0,3.0,10.0,True,True,True,167250001920
13,Qax_wUwb,تهرانسر شمالی,82.0,1404.0,2.0,3.0,True,True,True,16000000000
14,Qa7XgKy4,مرزداران,81.0,1404.0,2.0,7.0,True,True,True,12000000000
15,Qa7PhOTg,دریاچه شهدای خلیج فارس,109.0,1404.0,2.0,9.0,True,True,True,19540000768
16,gaDAd1n_,پونک,75.0,1384.0,2.0,0.0,True,True,False,18499999744
17,gaDc8oHa,هلال احمر,42.0,1396.0,1.0,4.0,False,True,True,5100000256
18,gaDcMaV8,ولنجک,230.0,1399.0,3.0,3.0,True,True,True,105999998976
19,gaDIIhOR,ارم,86.0,1387.0,2.0,3.0,True,True,True,18900000768

In [49]:
current_year = 1405
clean_data['Age'] = current_year - clean_data['Year']
clean_data['Price_per_meter'] = clean_data['Exact_Price'] / clean_data['Area']
clean_data = clean_data.drop(columns=['Year'])
clean_data.info()
clean_data.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9173 entries, 0 to 9172
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Token            9173 non-null   object
 1   District         9173 non-null   object
 2   Area             9173 non-null   float64
 3   Rooms            9173 non-null   float64
 4   Floor            9173 non-null   float64
 5   Parking          9173 non-null   bool
 6   Storage          9173 non-null   bool
 7   Elevator         9173 non-null   bool
 8   Exact_Price      9173 non-null   int64
 9   Age              9173 non-null   float64
 10  Price_per_meter  9173 non-null   float64
dtypes: bool(3), float64(5), int64(1), object(2)
memory usage: 600.3+ KB

,Token,District,Area,Rooms,Floor,Parking,Storage,Elevator,Exact_Price,Age,Price_per_meter
0,Qa1DsWJ1,جوانمردان (اندیشه),75.0,2.0,2.0,True,True,True,4819999744,5.0,6.426666e+07
1,Qawrev5W,خواجه نصیر طوسی,124.0,3.0,5.0,True,True,True,29699999744,2.0,2.395161e+08
2,gaDEeI84,ابوذر,55.0,1.0,2.0,False,False,False,8999999488,23.0,1.636364e+08
3,Qa9nZ1nq,خواجه نصیر طوسی,93.0,2.0,3.0,True,True,True,22320001024,2.0,2.400000e+08
4,Qa83KNv-,دریاچه شهدای خلیج فارس,100.0,2.0,15.0,True,True,True,2500000000,1.0,2.500000e+07
5,gaD4910f,تهرانپارس شرقی,125.0,2.0,3.0,True,True,True,18749999104,4.0,1.500000e+08
6,gaC8NaqF,زرگنده,165.0,3.0,0.0,True,True,True,51999997952,25.0,3.151515e+08
7,gaDs9Sss,استخر,75.0,2.0,2.0,True,True,True,14000000000,15.0,1.866667e+08
8,gaDstP3o,افسریه جنوبی,73.0,2.0,1.0,False,False,True,7900000256,6.0,1.082192e+08
9,Qa-rdUjz,دروس,213.0,3.0,5.0,True,True,True,138449993728,1.0,6.500000e+08
10,Qa-XNaIP,قلهک,147.0,2.0,9.0,True,True,True,124950003712,3.0,8.500000e+08
11,gaA8lFWY,دروس,240.0,3.0,6.0,True,True,True,204000002048,0.0,8.500000e+08
12,Qa_fwbHD,دروس,223.0,3.0,10.0,True,True,True,167250001920,3.0,7.500000e+08
13,Qax_wUwb,تهرانسر شمالی,82.0,2.0,3.0,True,True,True,16000000000,1.0,1.951220e+08
14,Qa7XgKy4,مرزداران,81.0,2.0,7.0,True,True,True,12000000000,1.0,1.481481e+08
15,Qa7PhOTg,دریاچه شهدای خلیج فارس,109.0,2.0,9.0,True,True,True,19540000768,1.0,1.792661e+08
16,gaDAd1n_,پونک,75.0,2.0,0.0,True,True,False,18499999744,21.0,2.466667e+08
17,gaDc8oHa,هلال احمر,42.0,1.0,4.0,False,True,True,5100000256,9.0,1.214286e+08
18,gaDcMaV8,ولنجک,230.0,3.0,3.0,True,True,True,105999998976,6.0,4.608696e+08
19,gaDIIhOR,ارم,86.0,2.0,3.0,True,True,True,18900000768,18.0,2.197675e+08

In [ ]:
import pandas as pd
import numpy as np

def remove_outliers_by_district(group):
    Q1_price = group['Price_per_meter'].quantile(0.25)
    Q3_price = group['Price_per_meter'].quantile(0.75)
    IQR_price = Q3_price - Q1_price
    lower_price = Q1_price - 1.5 * IQR_price
    upper_price = Q3_price + 1.5 * IQR_price

    Q1_area = group['Area'].quantile(0.25)
    Q3_area = group['Area'].quantile(0.75)
    IQR_area = Q3_area - Q1_area
    lower_area = Q1_area - 1.5 * IQR_area
    upper_area = Q3_area + 1.5 * IQR_area

    filtered_group = group[
        (group['Price_per_meter'] >= lower_price) &
        (group['Price_per_meter'] <= upper_price) &
        (group['Area'] >= lower_area) &
        (group['Area'] <= upper_area) &
        (group['Exact_Price'] >= 500_000_000) # حذف قیمت‌های به شدت پایین (زیر 500 میلیون)
    ]
    return filtered_group

final_data = clean_data.groupby('District').apply(remove_outliers_by_district)
final_data = final_data.reset_index(drop=True)
final_data.to_csv('cleaned_divar_data_grouped.csv', index=False, encoding='utf-8-sig')
print(f"All Data: {len(final_data)}")

All Data: 8416

/var/folders/33/1_9c8vl1123ffv0k7k3c_44c0000gn/T/ipykernel_17721/3617593124.py:26: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  final_data = clean_data.groupby('District').apply(remove_outliers_by_district)

In [51]:
final_data["District"].value_counts()

District
شهر زیبا        222
پونک            214
جیحون           208
دروس            172
شهرک چیتگر      168
               ...
امامت             1
والفجر            1
ترمینال جنوب      1
پارک شهر          1
شهرک شریفی        1
Name: count, Length: 352, dtype: int64